name: pycoalescence-environment
channels:
  - default
dependencies:
  - python
  - setuptools
  - numpy
  - pandas
  - scipy
  - gdal
  - libgdal
  - boost
  - libboost
  - cmake
  - sqlite
  - gxx_linux-64
  - matplotlib
