name: pycoalescence-environment
channels:
  - conda-forge
dependencies:
  - python
  - setuptools
  - numpy
  - pandas
  - scipy
  - gdal
  - libgdal
  - boost
  - libboost
  - cmake
  - sqlite
  - gxx_linux-64
  - pip:
    - numpy
    - scipy
    - matplotlib
    - pycoalescence