name: pycoalescence-environment
channels:
  - conda-forge
dependencies:
  - python
  - setuptools
  - numpy
  - pandas
  - gdal
  - libgdal
  - boost
  - libboost
  - cmake
  - sqlite
  - gxx_linux-64